<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Gida;
use Illuminate\Http\Request;

class GIDAController extends Controller
{
    public function index(){
        // $gida = [
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'barangay' => 'Barangay 1',
        //         'year' => 2023,
        //         'population' => 1207500,
        //         'ip_population' => 1000,
        //         'hrh' => 50,
        //         'wo_bhs' => 4,
        //         'wo_electricity' => 25,
        //         'wo_signal' => 6,
        //         'wo_internet' => 12,
        //         'proportion_sanitary' => 86,
        //         'proportion_water' => 91,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'barangay' => 'Barangay 3',
        //         'year' => 2022,
        //         'population' => 1007500,
        //         'ip_population' => 600,
        //         'hrh' => 40,
        //         'wo_bhs' => 10,
        //         'wo_electricity' => 35,
        //         'wo_signal' => 8,
        //         'wo_internet' => 10,
        //         'proportion_sanitary' => 86,
        //         'proportion_water' => 91,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'barangay' => 'Barangay 15',
        //         'year' => 2021,
        //         'population' => 167500,
        //         'ip_population' => 700,
        //         'hrh' => 40,
        //         'wo_bhs' => 10,
        //         'wo_electricity' => 35,
        //         'wo_signal' => 18,
        //         'wo_internet' => 13,
        //         'proportion_sanitary' => 54,
        //         'proportion_water' => 87,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'barangay' => 'Barangay 64',
        //         'year' => 2023,
        //         'population' => 1207500,
        //         'ip_population' => 55000,
        //         'hrh' => 150,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 20,
        //         'wo_signal' => 5,
        //         'wo_internet' => 10,
        //         'proportion_sanitary' => 88,
        //         'proportion_water' => 92,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'barangay' => 'Barangay 64',
        //         'year' => 2022,
        //         'population' => 807500,
        //         'ip_population' => 50000,
        //         'hrh' => 176,
        //         'wo_bhs' => 10,
        //         'wo_electricity' => 18,
        //         'wo_signal' => 18,
        //         'wo_internet' => 19,
        //         'proportion_sanitary' => 76,
        //         'proportion_water' => 99,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'barangay' => 'Barangay 64',
        //         'year' => 2021,
        //         'population' => 87500,
        //         'ip_population' => 43000,
        //         'hrh' => 654,
        //         'wo_bhs' => 123,
        //         'wo_electricity' => 42,
        //         'wo_signal' => 1,
        //         'wo_internet' => 51,
        //         'proportion_sanitary' => 99,
        //         'proportion_water' => 90,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'barangay' => 'Barangay 64',
        //         'year' => 2020,
        //         'population' => 107500,
        //         'ip_population' => 550,
        //         'hrh' => 150,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 20,
        //         'wo_signal' => 5,
        //         'wo_internet' => 10,
        //         'proportion_sanitary' => 88,
        //         'proportion_water' => 92,
        //     ],
        //     [
        //         'region' => 'CAR',
        //         'province' => 'Benguet',
        //         'city' => 'Baguio City',
        //         'barangay' => 'Barangay 198',
        //         'year' => 2023,
        //         'population' => 403500,
        //         'ip_population' => 20000,
        //         'hrh' => 60,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 10,
        //         'wo_signal' => 2,
        //         'wo_internet' => 5,
        //         'proportion_sanitary' => 84,
        //         'proportion_water' => 89,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Norte',
        //         'city' => 'Laoag City',
        //         'barangay' => 'Barangay 199',
        //         'year' => 2023,
        //         'population' => 355500,
        //         'ip_population' => 18000,
        //         'hrh' => 55,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 12,
        //         'wo_signal' => 3,
        //         'wo_internet' => 6,
        //         'proportion_sanitary' => 85,
        //         'proportion_water' => 90,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Norte',
        //         'city' => 'Laoag City',
        //         'barangay' => 'Barangay 19',
        //         'year' => 2023,
        //         'population' => 355500,
        //         'ip_population' => 15000,
        //         'hrh' => 45,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 8,
        //         'wo_signal' => 2,
        //         'wo_internet' => 4,
        //         'proportion_sanitary' => 87,
        //         'proportion_water' => 91,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Sur',
        //         'city' => 'Vigan City',
        //         'barangay' => 'Barangay 108',
        //         'year' => 2023,
        //         'population' => 219800,
        //         'ip_population' => 11000,
        //         'hrh' => 30,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 5,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 83,
        //         'proportion_water' => 89,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Sur',
        //         'city' => 'Vigan City',
        //         'barangay' => 'Barangay 10',
        //         'year' => 2023,
        //         'population' => 219800,
        //         'ip_population' => 10000,
        //         'hrh' => 25,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 4,
        //         'wo_signal' => 1,
        //         'wo_internet' => 2,
        //         'proportion_sanitary' => 85,
        //         'proportion_water' => 90,
        //     ],
        //     // Data for Region 2
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Cagayan',
        //         'city' => 'Tuguegarao City',
        //         'barangay' => 'Barangay 28',
        //         'year' => 2023,
        //         'population' => 454000,
        //         'ip_population' => 22000,
        //         'hrh' => 65,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 14,
        //         'wo_signal' => 4,
        //         'wo_internet' => 7,
        //         'proportion_sanitary' => 82,
        //         'proportion_water' => 88,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Cagayan',
        //         'city' => 'Tuguegarao City',
        //         'barangay' => 'Barangay 21',
        //         'year' => 2023,
        //         'population' => 454000,
        //         'ip_population' => 20000,
        //         'hrh' => 60,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 12,
        //         'wo_signal' => 3,
        //         'wo_internet' => 6,
        //         'proportion_sanitary' => 84,
        //         'proportion_water' => 89,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Isabela',
        //         'city' => 'Ilagan City',
        //         'barangay' => 'Barangay 21',
        //         'year' => 2023,
        //         'population' => 309600,
        //         'ip_population' => 16000,
        //         'hrh' => 45,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 10,
        //         'wo_signal' => 2,
        //         'wo_internet' => 5,
        //         'proportion_sanitary' => 83,
        //         'proportion_water' => 88,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Isabela',
        //         'city' => 'Ilagan City',
        //         'barangay' => 'Barangay 25',
        //         'year' => 2023,
        //         'population' => 309600,
        //         'ip_population' => 14000,
        //         'hrh' => 40,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 8,
        //         'wo_signal' => 1,
        //         'wo_internet' => 4,
        //         'proportion_sanitary' => 85,
        //         'proportion_water' => 89,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'barangay' => 'Barangay 31',
        //         'year' => 2023,
        //         'population' => 553350,
        //         'ip_population' => 28000,
        //         'hrh' => 75,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 16,
        //         'wo_signal' => 5,
        //         'wo_internet' => 8,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 85,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'barangay' => 'Barangay 32',
        //         'year' => 2023,
        //         'population' => 553350,
        //         'ip_population' => 25000,
        //         'hrh' => 70,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 14,
        //         'wo_signal' => 4,
        //         'wo_internet' => 7,
        //         'proportion_sanitary' => 82,
        //         'proportion_water' => 86,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Pampanga',
        //         'city' => 'San Fernando City',
        //         'barangay' => 'Barangay 33',
        //         'year' => 2023,
        //         'population' => 499650,
        //         'ip_population' => 25000,
        //         'hrh' => 60,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 12,
        //         'wo_signal' => 3,
        //         'wo_internet' => 6,
        //         'proportion_sanitary' => 81,
        //         'proportion_water' => 87,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Pampanga',
        //         'city' => 'San Fernando City',
        //         'barangay' => 'Barangay 34',
        //         'year' => 2023,
        //         'population' => 499650,
        //         'ip_population' => 20000,
        //         'hrh' => 55,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 10,
        //         'wo_signal' => 2,
        //         'wo_internet' => 5,
        //         'proportion_sanitary' => 83,
        //         'proportion_water' => 88,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'barangay' => 'Barangay 35',
        //         'year' => 2023,
        //         'population' => 553350,
        //         'ip_population' => 28000,
        //         'hrh' => 75,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 16,
        //         'wo_signal' => 5,
        //         'wo_internet' => 8,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 85,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'barangay' => 'Barangay 36',
        //         'year' => 2023,
        //         'population' => 553350,
        //         'ip_population' => 25000,
        //         'hrh' => 70,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 14,
        //         'wo_signal' => 4,
        //         'wo_internet' => 7,
        //         'proportion_sanitary' => 82,
        //         'proportion_water' => 86,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Pampanga',
        //         'city' => 'San Fernando City',
        //         'barangay' => 'Barangay 37',
        //         'year' => 2023,
        //         'population' => 499650,
        //         'ip_population' => 25000,
        //         'hrh' => 60,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 12,
        //         'wo_signal' => 3,
        //         'wo_internet' => 6,
        //         'proportion_sanitary' => 81,
        //         'proportion_water' => 87,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Pampanga',
        //         'city' => 'San Fernando City',
        //         'barangay' => 'Barangay 39',
        //         'year' => 2023,
        //         'population' => 499650,
        //         'ip_population' => 20000,
        //         'hrh' => 55,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 10,
        //         'wo_signal' => 2,
        //         'wo_internet' => 5,
        //         'proportion_sanitary' => 83,
        //         'proportion_water' => 88,
        //     ],
        //     [
        //         'region' => 'Region 4A',
        //         'province' => 'Cavite',
        //         'city' => 'Tagaytay City',
        //         'barangay' => 'Barangay 40',
        //         'year' => 2022,
        //         'population' => 207450,
        //         'ip_population' => 8000,
        //         'hrh' => 25,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 5,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 85,
        //         'proportion_water' => 90,
        //     ],
        //     [
        //         'region' => 'Region 4A',
        //         'province' => 'Cavite',
        //         'city' => 'Tagaytay City',
        //         'barangay' => 'Barangay 41',
        //         'year' => 2023,
        //         'population' => 207450,
        //         'ip_population' => 9000,
        //         'hrh' => 28,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 6,
        //         'wo_signal' => 2,
        //         'wo_internet' => 4,
        //         'proportion_sanitary' => 86,
        //         'proportion_water' => 91,
        //     ],
        //     [
        //         'region' => 'Region 4B',
        //         'province' => 'Palawan',
        //         'city' => 'Puerto Princesa City',
        //         'barangay' => 'Barangay 42',
        //         'year' => 2023,
        //         'population' => 412800,
        //         'ip_population' => 21000,
        //         'hrh' => 65,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 14,
        //         'wo_signal' => 4,
        //         'wo_internet' => 8,
        //         'proportion_sanitary' => 79,
        //         'proportion_water' => 84,
        //     ],
        //     [
        //         'region' => 'Region 4B',
        //         'province' => 'Palawan',
        //         'city' => 'Puerto Princesa City',
        //         'barangay' => 'Barangay 42',
        //         'year' => 2022,
        //         'population' => 412800,
        //         'ip_population' => 18000,
        //         'hrh' => 60,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 12,
        //         'wo_signal' => 3,
        //         'wo_internet' => 6,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 85,
        //     ],
        //     [
        //         'region' => 'Region 5',
        //         'province' => 'Albay',
        //         'city' => 'Legazpi City',
        //         'barangay' => 'Barangay 51',
        //         'year' => 2022,
        //         'population' => 309600,
        //         'ip_population' => 12000,
        //         'hrh' => 35,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 10,
        //         'wo_signal' => 1,
        //         'wo_internet' => 4,
        //         'proportion_sanitary' => 76,
        //         'proportion_water' => 82,
        //     ],
        //     [
        //         'region' => 'Region 6',
        //         'province' => 'Negros Occidental',
        //         'city' => 'Bacolod City',
        //         'barangay' => 'Barangay 65',
        //         'year' => 2023,
        //         'population' => 360150,
        //         'ip_population' => 18000,
        //         'hrh' => 50,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 15,
        //         'wo_signal' => 2,
        //         'wo_internet' => 6,
        //         'proportion_sanitary' => 78,
        //         'proportion_water' => 84,
        //     ],
        //     [
        //         'region' => 'Region 7',
        //         'province' => 'Cebu',
        //         'city' => 'Cebu City',
        //         'barangay' => 'Barangay 75',
        //         'year' => 2023,
        //         'population' => 606600,
        //         'ip_population' => 22000,
        //         'hrh' => 70,
        //         'wo_bhs' => 4,
        //         'wo_electricity' => 18,
        //         'wo_signal' => 3,
        //         'wo_internet' => 7,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 86,
        //     ],
        //     [
        //         'region' => 'Region 8',
        //         'province' => 'Leyte',
        //         'city' => 'Tacloban City',
        //         'barangay' => 'Barangay 86',
        //         'year' => 2023,
        //         'population' => 251550,
        //         'ip_population' => 10000,
        //         'hrh' => 30,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 8,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 75,
        //         'proportion_water' => 81,
        //     ],
        //     [
        //         'region' => 'Region 9',
        //         'province' => 'Zamboanga del Sur',
        //         'city' => 'Pagadian City',
        //         'barangay' => 'Barangay 97',
        //         'year' => 2023,
        //         'population' => 206040,
        //         'ip_population' => 3500,
        //         'hrh' => 18,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 5,
        //         'wo_signal' => 1,
        //         'wo_internet' => 2,
        //         'proportion_sanitary' => 78,
        //         'proportion_water' => 85,
        //     ],
        //     [
        //         'region' => 'Region 9',
        //         'province' => 'Zamboanga del Norte',
        //         'city' => 'Dipolog City',
        //         'barangay' => 'Barangay 98',
        //         'year' => 2022,
        //         'population' => 171660,
        //         'ip_population' => 7000,
        //         'hrh' => 25,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 6,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 87,
        //     ],
        //     [
        //         'region' => 'Region 10',
        //         'province' => 'Misamis Oriental',
        //         'city' => 'Cagayan de Oro City',
        //         'barangay' => 'Barangay 100',
        //         'year' => 2021,
        //         'population' => 350250,
        //         'ip_population' => 7000,
        //         'hrh' => 22,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 4,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 79,
        //         'proportion_water' => 84,
        //     ],
        //     [
        //         'region' => 'Region 10',
        //         'province' => 'Bukidnon',
        //         'city' => 'Valencia City',
        //         'barangay' => 'Barangay 101',
        //         'year' => 2023,
        //         'population' => 201420,
        //         'ip_population' => 10000,
        //         'hrh' => 30,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 5,
        //         'wo_signal' => 2,
        //         'wo_internet' => 4,
        //         'proportion_sanitary' => 82,
        //         'proportion_water' => 86,
        //     ],
        //     [
        //         'region' => 'Region 11',
        //         'province' => 'Davao del Sur',
        //         'city' => 'Davao City',
        //         'barangay' => 'Barangay 110',
        //         'year' => 2023,
        //         'population' => 472500,
        //         'ip_population' => 9000,
        //         'hrh' => 40,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 3,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 84,
        //         'proportion_water' => 88,
        //     ],
        //     [
        //         'region' => 'Region 11',
        //         'province' => 'Davao Oriental',
        //         'city' => 'Mati City',
        //         'barangay' => 'Barangay 111',
        //         'year' => 2022,
        //         'population' => 169200,
        //         'ip_population' => 5000,
        //         'hrh' => 20,
        //         'wo_bhs' => 1,
        //         'wo_electricity' => 4,
        //         'wo_signal' => 1,
        //         'wo_internet' => 2,
        //         'proportion_sanitary' => 81,
        //         'proportion_water' => 85,
        //     ],
        //     [
        //         'region' => 'Region 12',
        //         'province' => 'South Cotabato',
        //         'city' => 'Koronadal City',
        //         'barangay' => 'Barangay 125',
        //         'year' => 2023,
        //         'population' => 234000,
        //         'ip_population' => 14500,
        //         'hrh' => 42,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 5,
        //         'wo_signal' => 1,
        //         'wo_internet' => 2,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 85,
        //     ],
        //     [
        //         'region' => 'Region 12',
        //         'province' => 'Sultan Kudarat',
        //         'city' => 'Tacurong City',
        //         'barangay' => 'Barangay 123',
        //         'year' => 2022,
        //         'population' => 187000,
        //         'ip_population' => 10200,
        //         'hrh' => 35,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 3,
        //         'wo_signal' => 0,
        //         'wo_internet' => 1,
        //         'proportion_sanitary' => 78,
        //         'proportion_water' => 83,
        //     ],
        //     [
        //         'region' => 'BARMM',
        //         'province' => 'Lanao del Sur',
        //         'city' => 'Marawi City',
        //         'barangay' => 'Barangay 133',
        //         'year' => 2023,
        //         'population' => 201430,
        //         'ip_population' => 8000,
        //         'hrh' => 35,
        //         'wo_bhs' => 3,
        //         'wo_electricity' => 3,
        //         'wo_signal' => 1,
        //         'wo_internet' => 3,
        //         'proportion_sanitary' => 77,
        //         'proportion_water' => 82,
        //     ],
        //     [
        //         'region' => 'BARMM',
        //         'province' => 'Maguindanao',
        //         'city' => 'Cotabato City',
        //         'barangay' => 'Barangay 134',
        //         'year' => 2022,
        //         'population' => 299450,
        //         'ip_population' => 12000,
        //         'hrh' => 50,
        //         'wo_bhs' => 2,
        //         'wo_electricity' => 6,
        //         'wo_signal' => 2,
        //         'wo_internet' => 4,
        //         'proportion_sanitary' => 80,
        //         'proportion_water' => 85,
        //     ],
        // ];

        // Gida::insert($gida);

        $regions = Gida::distinct('region')->pluck('region');
            return view('mainpages/gida',[
                'regions' => $regions,
            ]
        );
    }

    public function getProvinces($region, $year)
    {
        $provinces = Gida::where('region', $region)->where('year', $year)->distinct('province')->pluck('province');
        return response()->json($provinces);
    }
    public function getCities($province, $year)
    {
        $cities = Gida::where('province', $province)->where('year', $year)->distinct('city')->pluck('city');
        return response()->json($cities);
    }
    public function getBarangays($city, $year)
    {
        $barangays = Gida::where('city', $city)->where('year', $year)->distinct('barangay')->pluck('barangay');
        return response()->json($barangays);
    }
    public function getInfo()
    {
        $info = Gida::all();
        return response()->json($info);
    }
}
