<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Lgu;
use Illuminate\Http\Request;

class LGUController extends Controller
{
    public function index(){
        // $lgu = [
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'year' => 2023,
        //         'tb_case' => 70500,
        //         'tb_treatment' => 43000,
        //         'safe_water' => 78.9,
        //         'stunting' => 56.4,
        //         'full_immune' => 40.78,
        //         'risk_philpen' => 12.5,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'year' => 2022,
        //         'tb_case' => 64500,
        //         'tb_treatment' => 41000,
        //         'safe_water' => 68.9,
        //         'stunting' => 53.4,
        //         'full_immune' => 41.78,
        //         'risk_philpen' => 11.2,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'year' => 2021,
        //         'tb_case' => 64100,
        //         'tb_treatment' => 35676,
        //         'safe_water' => 69,
        //         'stunting' => 56.9,
        //         'full_immune' => 44.23,
        //         'risk_philpen' => 10,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Quezon City',
        //         'year' => 2020,
        //         'tb_case' => 54100,
        //         'tb_treatment' => 31276,
        //         'safe_water' => 53.26,
        //         'stunting' => 23.9,
        //         'full_immune' => 10.5,
        //         'risk_philpen' => 25.5,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'year' => 2023,
        //         'tb_case' => 97100,
        //         'tb_treatment' => 57276,
        //         'safe_water' => 89.26,
        //         'stunting' => 59.9,
        //         'full_immune' => 67,
        //         'risk_philpen' => 14,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'year' => 2022,
        //         'tb_case' => 85100,
        //         'tb_treatment' => 45832,
        //         'safe_water' => 78.5,
        //         'stunting' => 45.5,
        //         'full_immune' => 40.6,
        //         'risk_philpen' => 9,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'year' => 2021,
        //         'tb_case' => 80500,
        //         'tb_treatment' => 40900,
        //         'safe_water' => 76,
        //         'stunting' => 46,
        //         'full_immune' => 79,
        //         'risk_philpen' => 15.70,
        //     ],
        //     [
        //         'region' => 'NCR',
        //         'province' => 'Metro Manila',
        //         'city' => 'Manila City',
        //         'year' => 2020,
        //         'tb_case' => 70500,
        //         'tb_treatment' => 39100,
        //         'safe_water' => 60,
        //         'stunting' => 49,
        //         'full_immune' => 78.25,
        //         'risk_philpen' => 13.90,
        //     ],
        //     [
        //         'region' => 'CAR',
        //         'province' => 'Mountain Province',
        //         'city' => 'Bontoc City',
        //         'year' => 2023,
        //         'tb_case' => 98765,
        //         'tb_treatment' => 12345,
        //         'safe_water' => 73.24,
        //         'stunting' => 12.75,
        //         'full_immune' => 45.83,
        //         'risk_philpen' => 9.62,
        //     ],
        //     [
        //         'region' => 'CAR',
        //         'province' => 'Kalinga',
        //         'city' => 'Tabuk City',
        //         'year' => 2023,
        //         'tb_case' => 54321,
        //         'tb_treatment' => 9876,
        //         'safe_water' => 88.57,
        //         'stunting' => 32.18,
        //         'full_immune' => 67.92,
        //         'risk_philpen' => 18.37,
        //     ],
        //     [
        //         'region' => 'CAR',
        //         'province' => 'Benguet',
        //         'city' => 'Baguio City',
        //         'year' => 2023,
        //         'tb_case' => 23456,
        //         'tb_treatment' => 6789,
        //         'safe_water' => 60.91,
        //         'stunting' => 21.46,
        //         'full_immune' => 38.79,
        //         'risk_philpen' => 5.94,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Norte',
        //         'city' => 'Laoag City',
        //         'year' => 2023,
        //         'tb_case' => 75432,
        //         'tb_treatment' => 5432,
        //         'safe_water' => 80.56,
        //         'stunting' => 15.27,
        //         'full_immune' => 52.44,
        //         'risk_philpen' => 10.83,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Norte',
        //         'city' => 'Laoag City',
        //         'year' => 2022,
        //         'tb_case' => 43210,
        //         'tb_treatment' => 8765,
        //         'safe_water' => 67.89,
        //         'stunting' => 28.91,
        //         'full_immune' => 41.73,
        //         'risk_philpen' => 8.75,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Sur',
        //         'city' => 'Vigan City',
        //         'year' => 2023,
        //         'tb_case' => 98765,
        //         'tb_treatment' => 2345,
        //         'safe_water' => 75.44,
        //         'stunting' => 10.92,
        //         'full_immune' => 48.26,
        //         'risk_philpen' => 9.14,
        //     ],
        //     [
        //         'region' => 'Region 1',
        //         'province' => 'Ilocos Sur',
        //         'city' => 'Vigan City',
        //         'year' => 2021,
        //         'tb_case' => 87654,
        //         'tb_treatment' => 3456,
        //         'safe_water' => 92.37,
        //         'stunting' => 5.63,
        //         'full_immune' => 67.11,
        //         'risk_philpen' => 14.29,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Cagayan',
        //         'city' => 'Tuguegarao City',
        //         'year' => 2023,
        //         'tb_case' => 54321,
        //         'tb_treatment' => 9876,
        //         'safe_water' => 84.91,
        //         'stunting' => 27.85,
        //         'full_immune' => 63.79,
        //         'risk_philpen' => 13.27,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Cagayan',
        //         'city' => 'Aparri City',
        //         'year' => 2023,
        //         'tb_case' => 87654,
        //         'tb_treatment' => 1234,
        //         'safe_water' => 65.73,
        //         'stunting' => 19.48,
        //         'full_immune' => 55.67,
        //         'risk_philpen' => 12.38,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Isabela',
        //         'city' => 'Ilagan City',
        //         'year' => 2023,
        //         'tb_case' => 65432,
        //         'tb_treatment' => 5678,
        //         'safe_water' => 73.21,
        //         'stunting' => 16.92,
        //         'full_immune' => 44.58,
        //         'risk_philpen' => 8.63,
        //     ],
        //     [
        //         'region' => 'Region 2',
        //         'province' => 'Isabela',
        //         'city' => 'Santiago City',
        //         'year' => 2023,
        //         'tb_case' => 76543,
        //         'tb_treatment' => 7890,
        //         'safe_water' => 90.08,
        //         'stunting' => 8.75,
        //         'full_immune' => 59.33,
        //         'risk_philpen' => 11.79,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'year' => 2023,
        //         'tb_case' => 65528,
        //         'tb_treatment' => 7892,
        //         'safe_water' => 84.56,
        //         'stunting' => 18.73,
        //         'full_immune' => 49.28,
        //         'risk_philpen' => 10.91,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'year' => 2020,
        //         'tb_case' => 73281,
        //         'tb_treatment' => 12324,
        //         'safe_water' => 45.4,
        //         'stunting' => 47.56,
        //         'full_immune' => 16.30,
        //         'risk_philpen' => 10.91,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Pampanga',
        //         'city' => 'San Fernando City',
        //         'year' => 2023,
        //         'tb_case' => 98231,
        //         'tb_treatment' => 67965,
        //         'safe_water' => 78.45,
        //         'stunting' => 65.98,
        //         'full_immune' => 20.50,
        //         'risk_philpen' => 15.78,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Pampanga',
        //         'city' => 'San Fernando City',
        //         'year' => 2022,
        //         'tb_case' => 37281,
        //         'tb_treatment' => 21324,
        //         'safe_water' => 45.4,
        //         'stunting' => 65.32,
        //         'full_immune' => 98.73,
        //         'risk_philpen' => 37.6,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'year' => 2023,
        //         'tb_case' => 53396,
        //         'tb_treatment' => 17878,
        //         'safe_water' => 65.32,
        //         'stunting' => 12.14,
        //         'full_immune' => 34.92,
        //         'risk_philpen' => 10.38,
        //     ],
        //     [
        //         'region' => 'Region 3',
        //         'province' => 'Bulacan',
        //         'city' => 'Malolos City',
        //         'year' => 2022,
        //         'tb_case' => 42396,
        //         'tb_treatment' => 5678,
        //         'safe_water' => 77.32,
        //         'stunting' => 22.14,
        //         'full_immune' => 44.92,
        //         'risk_philpen' => 9.38,
        //     ],
        //     [
        //         'region' => 'Region 4A',
        //         'province' => 'Cavite',
        //         'city' => 'Tagaytay City',
        //         'year' => 2023,
        //         'tb_case' => 83491,
        //         'tb_treatment' => 5123,
        //         'safe_water' => 78.93,
        //         'stunting' => 61.25,
        //         'full_immune' => 47.12,
        //         'risk_philpen' => 34.76,
        //     ],
        //     [
        //         'region' => 'Region 4A',
        //         'province' => 'Cavite',
        //         'city' => 'Dasmarinas City',
        //         'year' => 2023,
        //         'tb_case' => 26532,
        //         'tb_treatment' => 7347,
        //         'safe_water' => 92.57,
        //         'stunting' => 38.89,
        //         'full_immune' => 74.21,
        //         'risk_philpen' => 19.43,
        //     ],
        //     [
        //         'region' => 'Region 4A',
        //         'province' => 'Batangas',
        //         'city' => 'Batangas City',
        //         'year' => 2023,
        //         'tb_case' => 41832,
        //         'tb_treatment' => 8723,
        //         'safe_water' => 66.78,
        //         'stunting' => 24.53,
        //         'full_immune' => 83.11,
        //         'risk_philpen' => 51.24,
        //     ],
        //     [
        //         'region' => 'Region 4A',
        //         'province' => 'Batangas',
        //         'city' => 'Lipa City',
        //         'year' => 2023,
        //         'tb_case' => 68271,
        //         'tb_treatment' => 9312,
        //         'safe_water' => 41.36,
        //         'stunting' => 57.92,
        //         'full_immune' => 13.45,
        //         'risk_philpen' => 68.92,
        //     ],
        //     [
        //         'region' => 'Region 4B',
        //         'province' => 'Mindoro',
        //         'city' => 'Calapan City',
        //         'year' => 2023,
        //         'tb_case' => 58392,
        //         'tb_treatment' => 3867,
        //         'safe_water' => 74.25,
        //         'stunting' => 81.34,
        //         'full_immune' => 29.76,
        //         'risk_philpen' => 42.87,
        //     ],
        //     [
        //         'region' => 'Region 4B',
        //         'province' => 'Palawan',
        //         'city' => 'Puerto Princesa City',
        //         'year' => 2023,
        //         'tb_case' => 75213,
        //         'tb_treatment' => 5914,
        //         'safe_water' => 56.89,
        //         'stunting' => 45.23,
        //         'full_immune' => 92.51,
        //         'risk_philpen' => 15.67,
        //     ],
        //     [
        //         'region' => 'Region 5',
        //         'province' => 'Albay',
        //         'city' => 'Legazpi City',
        //         'year' => 2023,
        //         'tb_case' => 49251,
        //         'tb_treatment' => 3289,
        //         'safe_water' => 87.42,
        //         'stunting' => 68.57,
        //         'full_immune' => 36.71,
        //         'risk_philpen' => 74.19,
        //     ],
        //     [
        //         'region' => 'Region 5',
        //         'province' => 'Camarines Sur',
        //         'city' => 'Naga City',
        //         'year' => 2023,
        //         'tb_case' => 37129,
        //         'tb_treatment' => 2198,
        //         'safe_water' => 23.67,
        //         'stunting' => 94.13,
        //         'full_immune' => 59.38,
        //         'risk_philpen' => 26.84,
        //     ],
        //     [
        //         'region' => 'Region 6',
        //         'province' => 'Negros Occidental',
        //         'city' => 'Bacolod City',
        //         'year' => 2023,
        //         'tb_case' => 69241,
        //         'tb_treatment' => 5123,
        //         'safe_water' => 37.89,
        //         'stunting' => 15.67,
        //         'full_immune' => 72.14,
        //         'risk_philpen' => 82.45,
        //     ],
        //     [
        //         'region' => 'Region 7',
        //         'province' => 'Cebu',
        //         'city' => 'Cebu City',
        //         'year' => 2023,
        //         'tb_case' => 33162,
        //         'tb_treatment' => 2431,
        //         'safe_water' => 68.94,
        //         'stunting' => 73.26,
        //         'full_immune' => 45.79,
        //         'risk_philpen' => 39.51,
        //     ],
        //     [
        //         'region' => 'Region 8',
        //         'province' => 'Leyte',
        //         'city' => 'Tacloban City',
        //         'year' => 2023,
        //         'tb_case' => 42158,
        //         'tb_treatment' => 3229,
        //         'safe_water' => 54.27,
        //         'stunting' => 29.83,
        //         'full_immune' => 87.62,
        //         'risk_philpen' => 57.93,
        //     ],
        //     [
        //         'region' => 'Region 9',
        //         'province' => 'Zamboanga del Sur',
        //         'city' => 'Pagadian City',
        //         'year' => 2023,
        //         'tb_case' => 57231,
        //         'tb_treatment' => 3922,
        //         'safe_water' => 49.18,
        //         'stunting' => 12.67,
        //         'full_immune' => 61.25,
        //         'risk_philpen' => 18.34,
        //     ],
        //     [
        //         'region' => 'Region 9',
        //         'province' => 'Zamboanga del Norte',
        //         'city' => 'Dipolog City',
        //         'year' => 2022,
        //         'tb_case' => 78349,
        //         'tb_treatment' => 5432,
        //         'safe_water' => 82.71,
        //         'stunting' => 85.24,
        //         'full_immune' => 28.95,
        //         'risk_philpen' => 67.83,
        //     ],
        //     [
        //         'region' => 'Region 10',
        //         'province' => 'Misamis Oriental',
        //         'city' => 'Cagayan de Oro City',
        //         'year' => 2023,
        //         'tb_case' => 29384,
        //         'tb_treatment' => 2187,
        //         'safe_water' => 29.85,
        //         'stunting' => 41.62,
        //         'full_immune' => 73.27,
        //         'risk_philpen' => 38.14,
        //     ],
        //     [
        //         'region' => 'Region 10',
        //         'province' => 'Bukidnon',
        //         'city' => 'Valencia City',
        //         'year' => 2023,
        //         'tb_case' => 62547,
        //         'tb_treatment' => 4132,
        //         'safe_water' => 63.79,
        //         'stunting' => 52.84,
        //         'full_immune' => 14.76,
        //         'risk_philpen' => 95.28,
        //     ],
        //     [
        //         'region' => 'Region 11',
        //         'province' => 'Davao del Sur',
        //         'city' => 'Davao City',
        //         'year' => 2023,
        //         'tb_case' => 43219,
        //         'tb_treatment' => 2813,
        //         'safe_water' => 78.23,
        //         'stunting' => 64.79,
        //         'full_immune' => 39.56,
        //         'risk_philpen' => 27.84,
        //     ],
        //     [
        //         'region' => 'Region 11',
        //         'province' => 'Davao Oriental',
        //         'city' => 'Mati City',
        //         'year' => 2023,
        //         'tb_case' => 53291,
        //         'tb_treatment' => 3827,
        //         'safe_water' => 47.14,
        //         'stunting' => 36.82,
        //         'full_immune' => 84.75,
        //         'risk_philpen' => 59.34,
        //     ],
        //     [
        //         'region' => 'Region 12',
        //         'province' => 'South Cotabato',
        //         'city' => 'Koronadal City',
        //         'year' => 2023,
        //         'tb_case' => 81923,
        //         'tb_treatment' => 6123,
        //         'safe_water' => 57.84,
        //         'stunting' => 27.68,
        //         'full_immune' => 52.91,
        //         'risk_philpen' => 37.52,
        //     ],
        //     [
        //         'region' => 'Region 12',
        //         'province' => 'Sultan Kudarat',
        //         'city' => 'Tacurong City',
        //         'year' => 2023,
        //         'tb_case' => 71283,
        //         'tb_treatment' => 5092,
        //         'safe_water' => 68.25,
        //         'stunting' => 63.47,
        //         'full_immune' => 48.76,
        //         'risk_philpen' => 65.28,
        //     ],
        //     [
        //         'region' => 'BARMM',
        //         'province' => 'Lanao del Sur',
        //         'city' => 'Marawi City',
        //         'year' => 2023,
        //         'tb_case' => 62371,
        //         'tb_treatment' => 4128,
        //         'safe_water' => 39.87,
        //         'stunting' => 74.25,
        //         'full_immune' => 19.84,
        //         'risk_philpen' => 82.57,
        //     ],
        //     [
        //         'region' => 'BARMM',
        //         'province' => 'Maguindanao',
        //         'city' => 'Cotabato City',
        //         'year' => 2022,
        //         'tb_case' => 87231,
        //         'tb_treatment' => 6321,
        //         'safe_water' => 51.73,
        //         'stunting' => 32.91,
        //         'full_immune' => 64.28,
        //         'risk_philpen' => 47.63,
        //     ],
        // ];

        // Lgu::insert($lgu);

        $regions = Lgu::distinct('region')->pluck('region');
            return view('mainpages/lgu',[
                'regions' => $regions,
            ]
        );
    }
    public function getProvinces($region, $year)
    {
        $provinces = Lgu::where('region', $region)->where('year', $year)->distinct('province')->pluck('province');
        return response()->json($provinces);
    }
    public function getCities($province, $year)
    {
        $cities = Lgu::where('province', $province)->where('year', $year)->distinct('city')->pluck('city');
        return response()->json($cities);
    }
    public function getInfo()
    {
        $info = Lgu::all();
        return response()->json($info);
    }
}
